version: 2

models:
  - name: int_pay_buddy__companies_and_types.sql
    description: Companies known to Pay Buddy service with their type described. 
    columns:
      - name: company_id
        description: The unique identifier for a company. Primary key. 
        tests:
          - unique
          - not_null
      - name: company_type_id
        description: The code lookup to identifying a company as either a merchant or a buyer.
        tests:
          - not_null
      - name: company_name
        description: The registered trading name of a company.
        tests:
          - not_null
      - name: company_country
        description: The country in which a company is legally registered. 
        tests:
          - not_null
      - name: company_reference
        description: The reference to identify a company in legal registers.
        tests:
          - not_null
      - name: company_type
        description: Identifies a company as a merchant or a buyer.
        tests:
          - not_null

  - name: int_pay_buddy__payment_plan_decisions.sql
    description: Payment plans offered with the decisions taken by Pay Buddy's credit score engine. 
    columns:
      - name: payment_plan_id
        description: The unique identifier for a payment plan. Primary key. 
        tests:
          - unique
          - not_null
      - name: order_id
        description: The unique identifier for an order.
        tests:
          - not_null
      - name: agreement_id
        description: The unique identifier for an agreement.
        tests:
          - not_null
      - name: decision_type
        description: Whether a payment plan was accepted or refused by Pay Buddy. 
        tests:
          - not_null
      - name: decision_reason
        description: The precise reason for a decision if the payment plan is refused, 'accept' if  is accepted.
        tests:
          - not_null
      - name: term_in_days
        description: The number of days before repayment is due in full.
        tests:
          - not_null
