version: 2

models:
  - name: int_pay_buddy__companies_and_types.sql
    description: "Companies using the pay buddy service with their type"
    columns:
      - name: company_id
        description: "The unique identifier identifying a company"
        tests:
          - unique
          - not_null
      - name: company_type_id
        description: "The code lookup to identifying a company as either a merchant or a buyer"
        tests:
          - not_null
      - name: company_name
        description: "The registered name of a company"
        tests:
          - not_null
      - name: company_country
        description: "The country in which a company is registered"
        tests:
          - not_null
      - name: company_reference
        description: "The reference to identify a company in legal registers"
        tests:
          - not_null
      - name: company_type
        description: "Whether a company uses Pay Buddy as a merchant or as a buyer"
        tests:
          - not_null

  - name: int_pay_buddy__payment_plan_decisions.sql
    description: "Payment plans and the decisions taken on them"
    columns:
      - name: payment_plan_id
        description: "The unique identifier identifying a company"
        tests:
          - unique
          - not_null
      - name: order_id
        description: "The code lookup to identifying a company as either a merchant or a buyer"
        tests:
          - not_null
      - name: agreement_id
        description: "The registered name of a company"
        tests:
          - not_null
      - name: decision_type
        description: "The country in which a company is registered"
        tests:
          - not_null
      - name: decision_reason
        description: "The reference to identify a company in legal registers"
        tests:
          - not_null
      - name: term_in_days
        description: "The reference to identify a company in legal registers"
        tests:
          - not_null
