version: 2

sources:
  - name: pay_buddy_schema
    description: A replica of the production database used by the backend of Pay Buddy's product.
    tables:
      - name: raw_agreements
        description: The agreements between merchants and Pay Buddy. 
      - name: raw_companies
        description: Companies Pay Buddy has contact with. Contains both buyers and merchants. 
      - name: raw_company_type
        description: A lookup table referencing whether Pay Buddy knows a company as a merchant or as a buyer.
      - name: raw_decisions
        description: The decisions taken by Pay Buddy's credit engine.
      - name: raw_invoices
        description: Invoices issued by Pay Buddy to buyers whose payment plan was accepted.
      - name: raw_orders
        description: Orders made by buyers on marketplaces operated by merchants.
      - name: raw_payment_plan_templates
        description: Payment plan templates made available to merchants.
      - name: raw_payment_plans
        description: The payment plans buyers may pick from. 
      - name: raw_repayments
        description: Repayments made to Pay Buddy by buyers. 

models:
  - name: stg_pay_buddy__agreements
    description: The agreements between merchants and Pay Buddy. 
    columns:
      - name: agreement_id
        description: The unique identifier for an agreement. Primary key. 
        tests:
          - unique
          - not_null
      - name: merchant_id
        description: The unique identifier for an merchant.
        tests:
          - not_null
      - name: fee_percentage
        description: The percentage of each succesful order to be paid to Pay Buddy by the merchant.
        tests:
          - not_null

  - name: stg_pay_buddy__companies
    description: Companies Pay Buddy has contact with. Contains both buyers and merchants. 
    columns:
      - name: company_id
        description: The unique identifier for a company. Primary key. 
        tests:
          - unique
          - not_null
      - name: company_type_id
        description: The code lookup to identifying a company as either a merchant or a buyer.
        tests:
          - not_null
      - name: company_name
        description: The registered trading name of a company.
        tests:
          - not_null
      - name: company_country
        description: The country in which a company is legally registered. 
        tests:
          - not_null
      - name: company_reference
        description: The reference to identify a company in legal registers.
        tests:
          - not_null
  
  - name: stg_pay_buddy__company_type
    description: A lookup table referencing whether Pay Buddy knows a company as a merchant or as a buyer.
    columns:
      - name: company_type_id
        description: The unique identifier for a company type. Primary key. 
        tests:
          - unique
          - not_null
      - name: company_type
        description: Identifies a company as a merchant or a buyer.
        tests:
          - not_null
  
  - name: stg_pay_buddy__decisions
    description: The decisions taken by Pay Buddy's credit engine.
    columns:
      - name: decision_id
        description: The unique identifier for a decision. Primary key.  
        tests:
          - unique
          - not_null
      - name: decision_type
        description: Whether a payment plan was accepted or refused by Pay Buddy. 
        tests:
          - not_null
      - name: decision_reason
        description: The precise reason for a decision if the payment plan is refused, 'accept' if  is accepted.
        tests:
          - not_null

  - name: stg_pay_buddy__invoices
    description: Invoices issued by Pay Buddy to buyers whose payment plan was accepted. 
    columns:
      - name: invoice_id
        description: The unique identifier for an invoice. Primary key. 
        tests:
          - unique
          - not_null
      - name: buyer_id
        description: The unique identifier for a buyer.
        tests:
          - not_null
      - name: payment_plan_id
        description: The unique identifier for a payment plan.
        tests:
          - not_null
      - name: invoice_currency
        description: The currency in which the invoice is issued.
        tests:
          - not_null
      - name: invoice_amount
        description: The amount to be repaid to Pay Buddy.
        tests:
          - not_null
      - name: repayment_due_date
        description: The date by which the invoice amount is to be repaid in full. 
        tests:
          - not_null

  - name: stg_pay_buddy__orders
    description: Orders made by buyers on marketplaces operated by merchants. 
    columns:
      - name: order_id
        description: The unique identifier for an order. Primary key. 
        tests:
          - unique
          - not_null
      - name: buyer_id
        description: The unique identifier for a buyer. 
        tests:
          - not_null
      - name: merchant_id
        description: The unique identifier for a merchant.
        tests:
          - not_null
      - name: order_currency
        description: The currency in which the order is made.
        tests:
          - not_null
      - name: order_amount
        description: The amount paid to merchant for the goods and services purchased.
        tests:
          - not_null
      - name: order_date
        description: The date at which the order is made by the buyer.
        tests:
          - not_null

  - name: stg_pay_buddy__payment_plan_templates
    description: Payment plan templates made available to merchants. 
    columns:
      - name: payment_plan_template_id
        description: The unique identifier for a payment plan template. Primary key. 
        tests:
          - unique
          - not_null
      - name: agreement_id
        description: The unique identifier for an agreement.
        tests:
          - not_null
      - name: term_in_days
        description: The number of days before repayment is due in full.
        tests:
          - not_null

  - name: stg_pay_buddy__payment_plans
    description: The payment plans buyers may pick from. 
    columns:
      - name: payment_plan_id
        description: The unique identifier for a payment plan. Primary key.  
        tests:
          - unique
          - not_null
      - name: order_id
        description: The unique identifier for an order. 
        tests:
          - not_null
      - name: payment_plan_template_id
        description: The unique identifier for a payment plan template.
        tests:
          - not_null
      - name: decision_id
        description: The unique identifier for a decision. 
        tests:
          - not_null

  - name: stg_pay_buddy__repayments
    description: Repayments made to Pay Buddy by buyers. 
    columns:
      - name: repayment_id
        description: The unique identifier for a repayment. Primary key.  
        tests:
          - unique
          - not_null
      - name: invoice_id
        description: The unique identifier for an invoice.
        tests:
          - not_null
      - name: repayment_currency
        description: The currency in which a repayment is made.
        tests:
          - not_null
      - name: repayment_amount
        description: The amount repaid, either total or partial.
        tests:
          - not_null
      - name: repayment_date
        description: The date on which a repayment is made.
        tests:
          - not_null
