version: 2

sources:
  - name: pay_buddy_schema
    description: A replica of the production database used by the backend of Pay Buddy's product.
    tables:
      - name: raw_agreements
      - name: raw_companies
      - name: raw_company_type
      - name: raw_decisions
      - name: raw_invoices
      - name: raw_orders
      - name: raw_payment_plan_templates
      - name: raw_payment_plans
      - name: raw_repayments

models:
  - name: stg_pay_buddy__agreements.sql
    description: "Agreements"
    columns:
      - name: agreement_id
        description: "The unique identifier for this table"
        tests:
          - unique
          - not_null
      - name: merchant_id
        description: "The key to identify the merchant authorizing the payment scheme"
        tests:
          - not_null
      - name: fee_percentage
        description: "The percentage of the total transaction amount to be paid to Pay Buddy by the merchant"
        tests:
          - not_null

  - name: stg_pay_buddy__companies.sql
    description: "Companies using the pay buddy service"
    columns:
      - name: company_id
        description: "The unique identifier identifying a company"
        tests:
          - unique
          - not_null
      - name: company_type_id
        description: "The code lookup to identifying a company as either a merchant or a buyer"
        tests:
          - not_null
      - name: company_name
        description: "The registered name of a company"
        tests:
          - not_null
      - name: company_country
        description: "The country in which a company is registered"
        tests:
          - not_null
      - name: company_reference
        description: "The reference to identify a company in legal registers"
        tests:
          - not_null
  
  - name: stg_pay_buddy__company_type.sql
    description: "A table to identify whether a company uses Pay Buddy as a merchant or as a buyer"
    columns:
      - name: company_type_id
        description: "The unique identifier for this table"
        tests:
          - unique
          - not_null
      - name: company_type
        description: "Whether a company uses Pay Buddy as a merchant or as a buyer"
        tests:
          - not_null
  
  - name: stg_pay_buddy__decisions.sql
    description: "A table to keep track of decisions taken by Pay Buddy's credit engine"
    columns:
      - name: decision_id
        description: "The unique identifier for this table"
        tests:
          - unique
          - not_null
      - name: decision_type
        description: "Whether a payment plan was accepted or refused by Pay Buddy"
        tests:
          - not_null
      - name: decision_reason
        description: "The precise reason for a decision if it is refused (or 'accept' if the payment plan is accepted)"
        tests:
          - not_null

  - name: stg_pay_buddy__invoices.sql
    description: "A table to keep track of invoices issued by Pay Buddy to buyers"
    columns:
      - name: invoice_id
        description: "The unique identifier for this table"
        tests:
          - unique
          - not_null
      - name: buyer_id
        description: "The unique identifier to identify the buyer"
        tests:
          - not_null
      - name: payment_plan_id
        description: "The unique identifier to identify the payment plan chosen"
        tests:
          - not_null
      - name: invoice_currency
        description: "The currency in which the invoice is issued"
        tests:
          - not_null
      - name: invoice_amount
        description: "The amount to be repaid to Pay Buddy"
        tests:
          - not_null
      - name: repayment_due_date
        description: "The date by which the invoice amount is to be repaid to Pay Buddy"
        tests:
          - not_null

  - name: stg_pay_buddy__orders.sql
    description: "A table to keep track of orders made by buyers to merchants"
    columns:
      - name: order_id
        description: "The unique identifier for this table"
        tests:
          - unique
          - not_null
      - name: buyer_id
        description: "The unique identifier to identify the buyer"
        tests:
          - not_null
      - name: merchant_id
        description: "The unique identifier to identify the merchant"
        tests:
          - not_null
      - name: order_currency
        description: "The currency in which the order is made"
        tests:
          - not_null
      - name: order_amount
        description: "The amount to be paid to merchant for the goods or services ordered"
        tests:
          - not_null
      - name: order_date
        description: "The date at which the order is made"
        tests:
          - not_null

  - name: stg_pay_buddy__payment_plan_templates.sql
    description: "A table to keep track of the payment plan templates made available to merchants"
    columns:
      - name: payment_plan_template_id
        description: "The unique identifier for this table"
        tests:
          - unique
          - not_null
      - name: agreement_id
        description: "The unique identifier to identify the agreement to which the template applies"
        tests:
          - not_null
      - name: term_in_days
        description: "The number of days before repayment is due in full"
        tests:
          - not_null

  - name: stg_pay_buddy__payment_plans.sql
    description: "A table to keep track of the payment plans offered to buyers"
    columns:
      - name: payment_plan_id
        description: "The unique identifier for this table"
        tests:
          - unique
          - not_null
      - name: order_id
        description: "The unique identifier for the order for which this payment plan is offered"
        tests:
          - not_null
      - name: payment_plan_template_id
        description: "The unique identifier for the payment plan template offered"
        tests:
          - not_null
      - name: decision_id
        description: "The unique identifier for the decision taken by Pay Buddy for this particular payment plan"
        tests:
          - not_null

  - name: stg_pay_buddy__repayments.sql
    description: "A table to keep track of the repayments made to Pay Buddy by buyers"
    columns:
      - name: repayment_id
        description: "The unique identifier for this table"
        tests:
          - unique
          - not_null
      - name: invoice_id
        description: "The unique identifier for the invoice towards which this repayment is made"
        tests:
          - not_null
      - name: repayment_currency
        description: "The currency in which this repayment is made"
        tests:
          - not_null
      - name: repayment_amount
        description: "The amount repaid (can be total or partial)"
        tests:
          - not_null
      - name: repayment_date
        description: "The date on which this repayment is made"
        tests:
          - not_null
