pay_buddy_project:
  outputs:
    dev:
      dataset: pay_buddy_schema
      job_execution_timeout_seconds: 300
      job_retries: 1
      location: EU
      method: oauth
      priority: interactive
      project: pay-buddy-dbt-project
      threads: 1
      type: bigquery
  target: dev
