version: 2

models:
  - name: fact_invoices.sql
    description: "Invoices issued to buyers once a payment plan is accepted"
    columns:
      - name: invoice_id
        description: "The unique identifier identifying an invoice"
        tests:
          - unique
          - not_null
      - name: buyer_id
        description: "The unique identifier to identify the buyer"
      - name: payment_plan_id
        description: "The unique identifier to identify the payment plan chosen"
      - name: invoice_amount
        description: "The amount to be repaid to Pay Buddy"
      - name: repayment_amount
        description: "The amount repaid (can be total or partial)"
      - name: outstanding_amount
        description: "The amount repaid (can be total or partial)"
      - name: invoice_currency
        description: "The currency in which the invoice is issued"
      - name: repayment_due_date
        description: "The date by which the invoice amount is to be repaid to Pay Buddy"
      - name: repayment_date
        description: "The date on which this repayment is made"
  - name: fact_orders.sql
    description: "Final orders made by buyers once a decision is taken"
    columns:
      - name: order_id
        description: "The unique identifier identifying an order"
        tests:
          - unique
          - not_null
      - name: buyer_id
        description: "The unique identifier to identify the buyer"
      - name: merchant_id
        description: "The unique identifier to identify the payment plan chosen"
      - name: agreement_id
        description: "The amount to be repaid to Pay Buddy"
      - name: order_amount
        description: "The amount of the order"
      - name: order_date
        description: "The amount repaid (can be total or partial)"
      - name: is_accepted
        description: "The currency in which the invoice is issued"

  - name: fact_fees.sql
    description: "Final orders made by buyers once a decision is taken"
    columns:
      - name: fee_id
        description: "The unique identifier identifying an order"
        tests:
          - unique
          - not_null
      - name: merchant_id
        description: "The unique identifier to identify the payment plan chosen"
      - name: fee_percentage
        description: "The amount to be repaid to Pay Buddy"
      - name: order_amount
        description: "The amount of the order"
      - name: fee
        description: "The amount of the fee"
  - name: dim_merchants.sql
    description: "Merchants using the Pay Buddy service"
    columns:
      - name: merchant_id
        description: "The unique identifier identifying a merchant"
        tests:
          - unique
          - not_null
      - name: company_name
        description: "The unique identifier to identify the payment plan chosen"
      - name: company_country
        description: "The country in which the company is registered"
      - name: company_reference,
        description: "The legal reference of the company"
  - name: dim_buyers.sql
    description: "Buyers using the Pay Buddy service to purchase goods and services "
    columns:
      - name: buyer_id
        description: "The unique identifier identifying a merchant"
        tests:
          - unique
          - not_null
      - name: company_name
        description: "The unique identifier to identify the payment plan chosen"
      - name: company_country
        description: "The country in which the company is registered"
      - name: company_reference,
        description: "The legal reference of the company"
